### ISSUE TITLE
Reading FieldFE input slow down

### ISSUE THREAD

**Issue by Paulie14** [flow123d/flow123d#994]
I compared the speed of integration test for anisotropic tensor field - once set by constant, other time set using FieldFE/FieldElementwise, and I compared it between 2.2.1 and master, both are release builds.

- 2.2.1 - both tests are nearly the same, around 0.3s
- master
   - constant is about 1s
   - FieldFE 27s - the slow down is in assembly, I suppose when evaluating the field

I did not investigate the overall slow down, but the FieldFE slow down is critical.
I put the yaml files and results in:
```bacula.nti.tul.cz/intec/projekty/flow123d/input_data/SlowFieldFE/```

**Comment by jbrezmorf** [comment]
@Paulie14 

Problem probably in slow evaluation of FieldFE. This should be resolved with new assembly and further planned optimizations.

Make a new comparison (after DF_transport_asm merge to master), but for a field in TransportDG or Elasticity.
After new measurement, just postpone it to 4.0.0

**Comment by Paulie14** [comment]
New measurement in DG:
```
commit: 3d59ac732
N samples: 10
Profiler window: Whole Program
```

- constant: 0.46748776659999997
- FieldFE: 0.8097684709000001
- the factor is 1.73, much lower then before in case of DarcyFlow (there the problem persists due to old assembly)

results collected in:
`astra.cxi.tul.cz/Projekty/Modelari/flow123d/input_data/SlowFieldFE/`

**Comment by Paulie14** [comment]
TODO:
After implementing new assembly approach in all equations, do further measurements, possibly compare with older version.
(Note that comparison with older version might not be possible, e.g. due to problem with reading discont. data in DG..)

**Comment by jbrezmorf** [comment]
New assembly FieldFE have a minor impact on the assembly time for SCALAR FIELDS (see. [profiling results](https://docs.google.com/spreadsheets/d/1ZGHd0mDVEafIu4UnIy1lWukPAFZmQP3Yttn0A8A1WDk/edit#gid=0)).

Need a test with vector/tensor fields. There FieldFE evaluation includes the transformation of the basis (to the reference element). This might not be optimal yet. Moreover, for the symmetric tensors, it would be more efficient to apply the transform to the test function gradients. That means integrating over the reference element, but understanding vector-valued fe_values in the global coordinates.
